
GET http://localhost:8000/sermon/?keyword=communicate
Content-Type: application/json

###


GET http://localhost:8000/docs
Content-Type: application/json

###

GET http://localhost:8081/sermon/?keyword=communicate
Content-Type: application/json


###

GET http://localhost:8081/sermon/?keyword=communicate
Content-Type: application/json
